### ISSUE TITLE
it doesn't rotate the montiors properly

### ISSUE THREAD

**Issue by ITSZXY** [erans/hyprmon#24]
when  you set the transform it doesn't the width of the monitors so they overlap.
and it can't be adjusted through nwg-displays so about a quarter of the secondary monitor is inaccessible

<img width="899" height="434" alt="Image" src="https://github.com/user-attachments/assets/94be08ba-4f95-4fc4-84bb-46f7fbe1fdd0" />

**Comment by ITSZXY** [comment]
<img width="938" height="934" alt="Image" src="https://github.com/user-attachments/assets/3eaee24c-44b6-444a-ade2-617dfae1cb9d" />

<img width="309" height="65" alt="Image" src="https://github.com/user-attachments/assets/bcfe122f-d680-4234-9d70-d3d9a1fe00cd" />

sorry for the late reply i was extremely busy and yes the hdmi-a-2 is the vertical on the left and the dp-4 is in the middle

**Comment by Bookingyo** [comment]
Let's clean your monitor.conf a bit, no need for line 3 we can include the transform value in line 2

monitor = DP-4, 1920x1080@165.00, 0x0, 1
monitor = HDMI-A-2, 1280x1024@75.03, -1920x0, 1, transform, 1

You may want to adjust the 0 value in line 2 if your monitor is offset -1920x0 <<<<

I try to keep my main monitor at 0x0 this can help with some fullscreen programs.

Here are my configurations and my monitor is on my right side with a slight offset of -805 with vrr and hdr enabled on my main monitor.

monitor = DP-1, 3440x1440@164.899994, 0x0, 1, bitdepth, 10, cm, hdr, sdrbrightness, 1.2, sdrsaturation, 0.98, vrr, 3
monitor = DP-2, 2560x1440@144, 3440x-805, 1, transform, 3, bitdepth, 10

**Comment by erans** [comment]
I've pushed a new version that should correctly take rotation into account (And also visually show it).

**Comment by ITSZXY** [comment]
well it visually works 
<img width="1898" height="1017" alt="Image" src="https://github.com/user-attachments/assets/48ff0fe9-928e-48aa-9b55-b09536b23b7f" />
but when i save and exit and relaunch it goes back to being overlapped

<img width="1896" height="1022" alt="Image" src="https://github.com/user-attachments/assets/721b3475-69d3-4b03-8fd9-8e45a420b8b4" />

**Comment by ITSZXY** [comment]
even after removing the whole monitors.conf and removing hyprmon and using nwg-displays i still can't move my mouse to a quarter of the monitor

<img width="1894" height="1027" alt="Image" src="https://github.com/user-attachments/assets/98862a26-2b4f-4a30-ba6d-f8f698b7a386" />
the part highlighted

**Comment by erans** [comment]
@ITSZXY interesting. And with nwg-displays it also can't fix it?

**Comment by ITSZXY** [comment]
@erans doesn't fix it, but doesn't matter hyperland pooped itself today I am too busy to fix it

**Comment by erans** [comment]
@ITSZXY let me know if the newer version fixes this issue.

**Comment by ITSZXY** [comment]
@erans I reinstalled a while ago and it works fine now
